apiVersion: v1
kind: Service
metadata:
  name: petclinic-port-map
  labels:
    app: demo
spec:
  selector:
    app: petclinic-app
  type: NodePort
  ports:
  - nodePort: 32100
    port: 80
    targetPort: 8080
